#ifndef SCANWIDGETS_GLOBAL_H
#define SCANWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCANWIDGETS_LIBRARY)
#  define SCANWIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCANWIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCANWIDGETS_GLOBAL_H
