#ifndef QSCANPLUGIN_GLOBAL_H
#define QSCANPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSCANPLUGIN_LIBRARY)
#  define QSCANPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSCANPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSCANPLUGIN_GLOBAL_H
