#ifndef QSCANLOGGING_H
#define QSCANLOGGING_H

#include <QLoggingCategory>

//Q_DECLARE_LOGGING_CATEGORY(QscanSane)
Q_DECLARE_LOGGING_CATEGORY(QscanTwain)
Q_DECLARE_LOGGING_CATEGORY(QscanWidgets)
Q_DECLARE_LOGGING_CATEGORY(QscanScanner)
Q_DECLARE_LOGGING_CATEGORY(QscanOcr)
Q_DECLARE_LOGGING_CATEGORY(QScanUtil)

#endif // QSCANLOGGING_H
